services:
  postgres:
    container_name: db
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "develop"
    ports:
      - 54300:5432
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:

